### ISSUE TITLE
Hello sensei, I need you help with this code.

### ISSUE THREAD

**Issue by jid1311644** [YoshikiHigo/TinyPDG#2]
Hello sensei,I am a college student from China. I am sorry to bother you, I hope to get your help in your spare time.
We are learning about PDG recently. I was lucky to find out the code named TinyPDG that sensei pushed on Github in 2014. The problem is I'm too stupid to know how to run your code with my Eclipse and what I can do to generate a PDG of any piece of Java code.
I am so sorry for my poor English. I am grateful and look forward to your reply.Best wishes for you!

**Comment by YoshikiHigo** [comment]
Sorry for late replay and thank you for getting your interest in this tool.
Could you see Writer.java (https://github.com/YoshikiHigo/TinyPDG/blob/master/TinyPDG/src/yoshikihigo/tinypdg/graphviz/Writer.java)?
I think this file includes an answer to your question.
The code chunk from the 105th line to the 114th line and another code chunk from the 149th line to the 155th line might be helpful for your situation.

**Comment by jid1311644** [comment]
My problem has been solved, and I can already generate a PDG of java code. I really, really appreciate you taking the time to reply and help me.

**Comment by YoshikiHigo** [comment]
I'm happy to hear that.
